#! /bin/sh

bspc config border_width         0
bspc config window_gap          50

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config focus_follows_pointer true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true
bspc config auto_cancel true

#bspc config normal_border_color "#454444"
#bspc config urgent_border_color "#454444"
#bspc config focused_border_color "#676361"
#bspc config presel_feedback_color "#676361"


bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.0

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a urxvt-launcher state=floating
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a vlc desktop=^5 floating=on
bspc rule -a Steam desktop=^4
bspc rule -a Spotify desktop=^5 floating=on

bspc rule -a ipmiview desktop=^1 floating=on

syncthing &
